language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: mYrd8jhquy0NmMtGZW5tZVMbQUyXKUAH1uABmN2zB5CF2gIRrL7UKvtiRnbeFAiKzGDvmW+r3lWNdtC7iqBoEB0/sCPXKLyMUcYSiR0gDT/LzMjV3d+GUyPx1CC9bbJkSTJS1jEynq+hEv8eps0yRyhcFq/kqfJNWIU16hVmgYdxm3xPbQtpyAeaDaExamTBjj2hr49LzwAebYmmhEq/pOMe80ZKRqV7LhZNEju8hMSJvTOk0snLgwvZFCiaAxZd25m3RQOl40tRZ5I82EzSARkGrdAE2tvKDXNRSC2r6kxX0D24XifdKUloDK5K3U0AMtd5hWOu9pFIP9OXCqhWZgbr0J731HxKqLlNes7psaqqxWGpew59dMP6fiKJoGhVzEEzARExFGHWuHz6OvnqVHTxtgDFDOSpCRlxI2wkyQnf038y3JGaQAV69T8s6MQxfuNM36ThRmD/Mj4KhuKdCyuJPtysHvYj41xOWP6mKtISVnv7dqRa6qi6laYgObo00+diQ7IzNM9x3LKs6ueEBseFJX2aMHgskEEWjRBg3bIOaV2V1HkYy2FQgk8PP455nj9kOFev9SvdLzvHcWp5qQienI+j6Rt/TrBnTu6ySQM1vRJSCg8F1HE1XYnuNMNRc16oc5IuyIEa3Nt+7q7GDYkmu0TO4la6ICKa2PVM0sI=
  - secure: nH+ZXDMs22URkKk0WVckSin3NTi/oV7vD39N5G59/tC3gm3FuBsJefAto9BrdO1T47UOsK0HKF9VGsCdMze/zGTzrpa8dDd7ArvoCzbhKGasMA+PXrAQYXt9/k9TBBOyH+nIAcDi6iSzK+6UEi+bKAGhOkINc6fjfuJr6JOzDYc1SwTukgjrtvxccOof+FNqHN2KjzZ4hOmsrRnfEjnsmkRQkRb83X+n7bE9NooLRTPPZ5yhBuia39xVUoTA/9bITte52XWpctBk8z2b3+j3ydCZvkNJDWhyATXhDXWFyJyFBPdec7kBGgkBJZGSCnwBodpvn+Q1nfdQ9OTMLCYQ0cynoctT95cmZBADvEd8/r931+7wXZDIWCNxrJ4qZ0rcAElmBHyqY+oncCW5bX9PdxLYMLkS0Rl2aM8vNmCOE1bPEYljktL6nP0L+IdY9A+jogR/rNhO8cRSAWYjxoElpTiACgnnfoIhDEaUJU/RsCHF0Xk89PzGEyOGi7czSi5pK5zXZUlMu8HzlDaeT+reXhqMIplctVaHUQk7hoed9b8z5OvK3PLYqBjpbjKZFb3NL29ciuXiKtbFUrZ0OHCrc80WChXU1/dC5V7N9Nky3A69pkTRzJy384mgDbYht1UBjFQYUgC9Ey9crJo2a7tAVmbGYTiq3PqLmZfVE1YhDQU=
  - secure: o+nNeMFeVJU2hXb1juDkmgaRa8gA5r9zunaCdVs1Vy1pK66/Q70QW7fOGRlgY9M7UggVlMz2Nc4MoyuiVYtJI6bzhuyK1OGQT/7DWumf3P1tpJY2otcuLhg3Xbaz+hWhpa2f8I2sAzVMBXgeXDzpJ5VcL6jMAz/RHsTebGHI0HRQxkw6HqUALWiLtwtirF0HF463lxAlT3lcIj+vsnvWF/8qtkJnwlR5Expm9re+37JRaM6u2SUXMaBBg+7qbExXJO2QfbVBreuiF9D97ed04yDpkuFdU0oVEunSpXq53OpQDw/MMN+MNgKC2WugBL7Rh940K2DGKIbqP+37bMafeEeLhKMFC7KbTtKWqt6HUxxMaRl/Tz7zbNQ33ascqa75AsknPLMoY/b+m8LDoJeVVPj1xnGE3YAwhd/0lsRcorKEyum9aWLzTw65gu77PD7TMo9J2wDA7a0HCIfmn0eCrnr9iUOQ6JEepxev7mNGwkBS6Fnx0v1HZELWmGwqDiTGcStmaWNLafU2kcXrLN4WD9chxeutQTDEl/4SItceyfATwyydgvrL7j/iysCYhlfcA29ZOAn6gn+8jaFWWcQTyODodNqXis6C4jt27i9xLyDP2VmUqie0QnvSeAkHZfc6s5NcxRGSYlw/kGR5oKXSlsoDmrSy9MNadegn2y3EwMw=
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
